namespace MotoSOS.API.Modules.TelemetrySummary.Contracts;

public sealed record TelemetrySummaryResponse(
    string Id,
    string UserId,
    string TripId,
    string VehicleId,
    string TripStatus,
    string SummaryStatus,
    int TotalMinorEvents,
    IReadOnlyDictionary<string, int> EventsByType,
    IReadOnlyDictionary<string, int> EventsBySeverity,
    IReadOnlyDictionary<string, int> EventsBySource,
    IReadOnlyDictionary<string, int> EventsByStatus,
    int HardBrakeCount,
    int HarshAccelerationCount,
    int SharpTurnCount,
    int GpsSignalLostCount,
    int GpsSignalRecoveredCount,
    int LowBatteryCount,
    int SmartwatchDisconnectedCount,
    int SmartwatchReconnectedCount,
    int SensorAnomalyCount,
    int PossibleFallLowConfidenceCount,
    int InformationalCount,
    DateTimeOffset? FirstEventAtUtc,
    DateTimeOffset? LastEventAtUtc,
    double? AverageConfidence,
    double? MaxScore,
    double? AverageScore,
    int? MinBatteryLevel,
    double? MaxSpeedKmh,
    IReadOnlyDictionary<string, int> GpsQualitySamples,
    DateTimeOffset LastComputedAtUtc,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? UpdatedAtUtc);
