using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using FluentAssertions;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using MotoSOS.API.Modules.AlertAcknowledgements.Application;
using MotoSOS.API.Modules.AlertAcknowledgements.Domain;
using MotoSOS.API.Modules.AlertDispatch.Application;
using MotoSOS.API.Modules.AlertDispatch.Domain;
using MotoSOS.API.Modules.AuditLogs.Application;
using MotoSOS.API.Modules.AuditLogs.Domain;
using MotoSOS.API.Modules.Auth.Application;
using MotoSOS.API.Modules.Auth.Contracts;
using MotoSOS.API.Modules.Auth.Domain;
using MotoSOS.API.Modules.EmergencyContacts.Domain;
using MotoSOS.API.Modules.EmergencyResolution.Application;
using MotoSOS.API.Modules.EmergencyResolution.Domain;
using MotoSOS.API.Modules.Escalations.Application;
using MotoSOS.API.Modules.Escalations.Domain;
using MotoSOS.API.Modules.EvidenceAttachments.Application;
using MotoSOS.API.Modules.EvidenceAttachments.Domain;
using MotoSOS.API.Modules.Incidents.Application;
using MotoSOS.API.Modules.Incidents.Domain;
using MotoSOS.API.Modules.LocationSharing.Application;
using MotoSOS.API.Modules.LocationSharing.Domain;
using MotoSOS.API.Modules.Notifications.Application;
using MotoSOS.API.Modules.Notifications.Domain;
using MotoSOS.API.Modules.ReportExports.Application;
using MotoSOS.API.Modules.ReportExports.Domain;
using MotoSOS.API.Modules.TelemetrySummary.Application;
using MotoSOS.API.Modules.TelemetrySummary.Domain;
using MotoSOS.API.Modules.Trips.Application;
using MotoSOS.API.Modules.Trips.Domain;
using MotoSOS.API.Modules.Users.Application;
using MotoSOS.API.Modules.Users.Domain;

namespace IntegrationTest;

public sealed class ResolutionReportExportEndpointsTests
{
    [Fact]
    public async Task ExportEndpointsRequireAuthentication()
    {
        await using WebApplicationFactory<Program> factory = CreateFactory(new Stores());
        HttpClient client = factory.CreateClient();
        (await client.GetAsync("/api/v1/rider/emergencies/incident/resolution-report/export")).StatusCode.Should().Be(HttpStatusCode.Unauthorized);
        (await client.GetAsync("/api/v1/admin/resolution-report-exports")).StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task RiderAdminAndMonitorExportStructuredJsonWithSafeResponse()
    {
        var stores = new Stores(); await using WebApplicationFactory<Program> factory = CreateFactory(stores); HttpClient rider = factory.CreateClient(); HttpClient admin = factory.CreateClient(); HttpClient monitor = factory.CreateClient(); User riderUser = await AuthenticateAsync(rider, "export-rider@example.com", UserRole.Rider, stores); await AuthenticateAsync(admin, "export-admin@example.com", UserRole.Admin, stores); User monitorUser = await AuthenticateAsync(monitor, "export-monitor@example.com", UserRole.Monitor, stores); Seed(stores, riderUser.Id, monitorUser.Id);

        string riderBody = await (await rider.GetAsync("/api/v1/rider/emergencies/incident/resolution-report/export")).Content.ReadAsStringAsync();

        riderBody.Should().Contain("incidentSummary").And.Contain("evidenceSummary").And.NotContain("clientStorageReference").And.NotContain("base64").And.NotContain("polyline");
        (await admin.GetAsync("/api/v1/admin/emergencies/incident/resolution-report/export")).StatusCode.Should().Be(HttpStatusCode.OK);
        (await monitor.GetAsync("/api/v1/monitor/alerts/attempt/resolution-report/export")).StatusCode.Should().Be(HttpStatusCode.OK);
        (await admin.GetAsync("/api/v1/admin/resolution-report-exports")).StatusCode.Should().Be(HttpStatusCode.OK);
        stores.Exports.Items.Should().ContainSingle();
    }

    [Fact]
    public async Task ForeignRiderUnassignedMonitorAndInvalidExportTypeAreRejected()
    {
        var stores = new Stores(); await using WebApplicationFactory<Program> factory = CreateFactory(stores); HttpClient rider = factory.CreateClient(); HttpClient other = factory.CreateClient(); HttpClient monitor = factory.CreateClient(); User riderUser = await AuthenticateAsync(rider, "export-owner@example.com", UserRole.Rider, stores); await AuthenticateAsync(other, "export-other@example.com", UserRole.Rider, stores); await AuthenticateAsync(monitor, "export-monitor2@example.com", UserRole.Monitor, stores); Seed(stores, riderUser.Id, null);

        (await other.GetAsync("/api/v1/rider/emergencies/incident/resolution-report/export")).StatusCode.Should().Be(HttpStatusCode.NotFound);
        (await monitor.GetAsync("/api/v1/monitor/alerts/attempt/resolution-report/export")).StatusCode.Should().Be(HttpStatusCode.NotFound);
        (await rider.GetAsync("/api/v1/rider/emergencies/incident/resolution-report/export?exportType=PDF")).StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    private static readonly DateTimeOffset Now = new(2026, 8, 9, 12, 0, 0, TimeSpan.Zero);
    private static void Seed(Stores s, string userId, string? monitorId) { s.Incidents.Items.Add(new Incident { Id = "incident", UserId = userId, TripId = "trip", Status = IncidentStatus.Closed, Cause = IncidentCause.CountdownTimeout, RiskLevel = IncidentRiskLevel.High, OccurredAtUtc = Now, CreatedAtUtc = Now, ClosedAtUtc = Now }); s.Trips.Items.Add(new Trip { Id = "trip", UserId = userId, VehicleId = "vehicle", Status = TripStatus.Finished, StartedAtUtc = Now.AddHours(-1), FinishedAtUtc = Now }); s.Alerts.Items.Add(new AlertDispatchRequest { Id = "alert", UserId = userId, IncidentId = "incident", TripId = "trip", Status = AlertDispatchStatus.Completed, CreatedAtUtc = Now }); s.Reports.Items.Add(new EmergencyResolutionReport { Id = "report", UserId = userId, IncidentId = "incident", TripId = "trip", AlertDispatchId = "alert", Outcome = EmergencyResolutionOutcome.RealEmergency, ClosedByRole = EmergencyClosedByRole.Rider, Summary = "safe", CreatedAtUtc = Now }); s.Attempts.Items.Add(new NotificationDeliveryAttempt { Id = "attempt", UserId = userId, IncidentId = "incident", AlertDispatchId = "alert", TripId = "trip", EmergencyContactId = "contact", Status = NotificationDeliveryStatus.Prepared }); s.Evidence.Items.Add(new EvidenceAttachment { Id = "evidence", UserId = userId, IncidentId = "incident", TargetType = EvidenceTargetType.Incident, EvidenceType = EvidenceType.Photo, Source = EvidenceSource.RiderMobileApp, Status = EvidenceAttachmentStatus.Registered, FileName = "photo.jpg", ContentType = "image/jpeg", SizeBytes = 1, RegisteredByRole = UserRole.Rider, CapturedAtUtc = Now, CreatedAtUtc = Now, ClientEvidenceId = "client" }); if (monitorId is not null) s.Contacts.Items.Add(new EmergencyContact { Id = "contact", LinkedUserId = monitorId, IsActive = true, InvitationStatus = EmergencyContactInvitationStatus.Linked }); }
    private static async Task<User> AuthenticateAsync(HttpClient client, string email, UserRole role, Stores stores) { var register = new RegisterRequest(email, "StrongPass1!", "StrongPass1!", "Moto Rider", "+52 555", "Rider", true); await client.PostAsJsonAsync("/api/v1/auth/register", register); User user = stores.Users.Items.Single(u => u.Email == email); user.Role = role; LoginEnvelope login = (await (await client.PostAsJsonAsync("/api/v1/auth/login", new LoginRequest(email, register.Password))).Content.ReadFromJsonAsync<LoginEnvelope>())!; client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", login.Data.AccessToken); return user; }
    private static WebApplicationFactory<Program> CreateFactory(Stores stores) => new WebApplicationFactory<Program>().WithWebHostBuilder(builder => { builder.UseEnvironment("Testing"); builder.ConfigureAppConfiguration((_, c) => c.AddInMemoryCollection(new Dictionary<string, string?> { ["Jwt:Issuer"] = "MotoSOS", ["Jwt:Audience"] = "MotoSOS.Clients", ["Jwt:Key"] = new string('X', 48), ["Jwt:AccessTokenMinutes"] = "15", ["Jwt:RefreshTokenDays"] = "7", ["Jwt:RefreshTokenRememberMeDays"] = "30", ["MongoDb:" + "Connection" + "String"] = string.Empty, ["MongoDb:DatabaseName"] = "MotoSOS_Test" })); builder.ConfigureTestServices(services => { services.AddSingleton<IUserRepository>(stores.Users); services.AddSingleton<IRefreshTokenRepository>(stores.RefreshTokens); services.AddSingleton<IIncidentRepository>(stores.Incidents); services.AddSingleton<ITripRepository>(stores.Trips); services.AddSingleton<IAlertDispatchRepository>(stores.Alerts); services.AddSingleton<IEmergencyResolutionRepository>(stores.Reports); services.AddSingleton<INotificationDeliveryAttemptRepository>(stores.Attempts); services.AddSingleton<INotificationAttemptMonitorRepository>(stores.Attempts); services.AddSingleton<IAlertAcknowledgementRepository>(stores.Acks); services.AddSingleton<ILocationSharingRepository>(stores.Locations); services.AddSingleton<IEmergencyEscalationRepository>(stores.Escalations); services.AddSingleton<ITelemetrySummaryRepository>(stores.Telemetry); services.AddSingleton<IEvidenceAttachmentRepository>(stores.Evidence); services.AddSingleton<IMonitorLinkedContactRepository>(stores.Contacts); services.AddSingleton<IAuditLogRepository>(stores.AuditLogs); services.AddSingleton<IResolutionReportExportRepository>(stores.Exports); }); });
    private sealed record LoginEnvelope(bool Success, LoginResponse Data);
    private sealed class Stores { public Users Users { get; } = new(); public RefreshTokens RefreshTokens { get; } = new(); public Incidents Incidents { get; } = new(); public Trips Trips { get; } = new(); public Alerts Alerts { get; } = new(); public Reports Reports { get; } = new(); public Attempts Attempts { get; } = new(); public Acks Acks { get; } = new(); public Locations Locations { get; } = new(); public Escalations Escalations { get; } = new(); public Telemetry Telemetry { get; } = new(); public Evidence Evidence { get; } = new(); public Contacts Contacts { get; } = new(); public AuditLogs AuditLogs { get; } = new(); public Exports Exports { get; } = new(); }
    private sealed class Users : IUserRepository { public List<User> Items { get; } = []; public Task<User?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(u => u.Id == id)); public Task<User?> GetByEmailAsync(string email, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(u => u.Email == email)); public Task AddAsync(User u, CancellationToken ct) { Items.Add(u); return Task.CompletedTask; } public Task UpdateAsync(User u, CancellationToken ct) => Task.CompletedTask; }
    private sealed class RefreshTokens : IRefreshTokenRepository { public List<RefreshToken> Items { get; } = []; public Task<RefreshToken?> GetByHashAsync(string h, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(t => t.TokenHash == h)); public Task AddAsync(RefreshToken t, CancellationToken ct) { Items.Add(t); return Task.CompletedTask; } public Task UpdateAsync(RefreshToken t, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Incidents : IIncidentRepository { public List<Incident> Items { get; } = []; public Task<Incident?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(i => i.Id == id)); public Task<Incident?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<Incident?>(null); public Task<(Incident Incident, bool IsDuplicate)> AddOrGetDuplicateAsync(Incident i, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<Incident>> ListByUserIdAsync(string u, IncidentStatus? s, string? t, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<Incident>>([]); public Task<long> CountByUserIdAsync(string u, IncidentStatus? s, string? t, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(Incident i, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Trips : ITripRepository { public List<Trip> Items { get; } = []; public Task<Trip?> GetActiveByUserIdAsync(string u, CancellationToken ct) => Task.FromResult<Trip?>(null); public Task<Trip?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(t => t.Id == id)); public Task<IReadOnlyList<Trip>> ListByUserIdAsync(string u, TripStatus? s, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<Trip>>([]); public Task<long> CountByUserIdAsync(string u, TripStatus? s, CancellationToken ct) => Task.FromResult(0L); public Task AddAsync(Trip t, CancellationToken ct) => Task.CompletedTask; public Task UpdateAsync(Trip t, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Alerts : IAlertDispatchRepository { public List<AlertDispatchRequest> Items { get; } = []; public Task<AlertDispatchRequest?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(a => a.Id == id)); public Task<AlertDispatchRequest?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<AlertDispatchRequest?>(null); public Task<(AlertDispatchRequest AlertDispatch, bool IsDuplicate)> AddOrGetDuplicateAsync(AlertDispatchRequest a, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<AlertDispatchRequest>> ListByUserIdAsync(string u, AlertDispatchStatus? s, string? i, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<AlertDispatchRequest>>(Items.Where(a => a.UserId == u && (i is null || a.IncidentId == i)).ToArray()); public Task<long> CountByUserIdAsync(string u, AlertDispatchStatus? s, string? i, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(AlertDispatchRequest a, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Reports : IEmergencyResolutionRepository { public List<EmergencyResolutionReport> Items { get; } = []; public Task<EmergencyResolutionReport?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(r => r.Id == id)); public Task<EmergencyResolutionReport?> GetByIncidentIdAsync(string i, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(r => r.IncidentId == i)); public Task<EmergencyResolutionReport?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<EmergencyResolutionReport?>(null); public Task<(EmergencyResolutionReport Report, bool IsDuplicate)> AddOrGetDuplicateAsync(EmergencyResolutionReport r, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<EmergencyResolutionReport>> ListByUserIdAsync(string u, EmergencyResolutionOutcome? o, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<EmergencyResolutionReport>>([]); public Task<long> CountByUserIdAsync(string u, EmergencyResolutionOutcome? o, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class Attempts : INotificationDeliveryAttemptRepository, INotificationAttemptMonitorRepository { public List<NotificationDeliveryAttempt> Items { get; } = []; public Task<NotificationDeliveryAttempt?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(a => a.Id == id)); public Task<NotificationDeliveryAttempt?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<NotificationDeliveryAttempt?>(null); public Task<(NotificationDeliveryAttempt Attempt, bool IsDuplicate)> AddOrGetDuplicateAsync(NotificationDeliveryAttempt a, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<NotificationDeliveryAttempt>> ListByUserIdAsync(string u, string? a, string? i, NotificationDeliveryStatus? s, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<NotificationDeliveryAttempt>>(Items.Where(n => n.UserId == u && (a is null || n.AlertDispatchId == a) && (i is null || n.IncidentId == i)).ToArray()); public Task<long> CountByUserIdAsync(string u, string? a, string? i, NotificationDeliveryStatus? s, CancellationToken ct) => Task.FromResult(0L); public Task<IReadOnlyList<NotificationDeliveryAttempt>> ListByEmergencyContactIdsAsync(IReadOnlyCollection<string> ids, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<NotificationDeliveryAttempt>>([]); public Task<long> CountByEmergencyContactIdsAsync(IReadOnlyCollection<string> ids, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(NotificationDeliveryAttempt a, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Acks : IAlertAcknowledgementRepository { public Task<AlertAcknowledgement?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<AlertAcknowledgement?>(null); public Task<AlertAcknowledgement?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<AlertAcknowledgement?>(null); public Task<(AlertAcknowledgement Acknowledgement, bool IsDuplicate)> AddOrGetDuplicateAsync(AlertAcknowledgement a, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<AlertAcknowledgement>> ListByMonitorUserIdAsync(string m, AlertAcknowledgementStatus? s, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<AlertAcknowledgement>>([]); public Task<long> CountByMonitorUserIdAsync(string m, AlertAcknowledgementStatus? s, CancellationToken ct) => Task.FromResult(0L); public Task<IReadOnlyList<AlertAcknowledgement>> ListByUserIdAsync(string u, string? a, string? i, AlertAcknowledgementStatus? s, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<AlertAcknowledgement>>([]); public Task<long> CountByUserIdAsync(string u, string? a, string? i, AlertAcknowledgementStatus? s, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(AlertAcknowledgement a, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Locations : ILocationSharingRepository { public Task<EmergencyLocationSnapshot?> GetByUserIdAndIncidentIdAsync(string u, string i, CancellationToken ct) => Task.FromResult<EmergencyLocationSnapshot?>(null); public Task<EmergencyLocationSnapshot?> GetActiveByIncidentIdAsync(string i, CancellationToken ct) => Task.FromResult<EmergencyLocationSnapshot?>(null); public Task<EmergencyLocationSnapshot?> GetLatestByIncidentIdAsync(string i, CancellationToken ct) => Task.FromResult<EmergencyLocationSnapshot?>(null); public Task<EmergencyLocationSnapshot> UpsertLatestAsync(EmergencyLocationSnapshot s, CancellationToken ct) => Task.FromResult(s); }
    private sealed class Escalations : IEmergencyEscalationRepository { public Task<EmergencyEscalation?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<EmergencyEscalation?>(null); public Task<EmergencyEscalation?> GetByAlertDispatchIdAsync(string id, CancellationToken ct) => Task.FromResult<EmergencyEscalation?>(null); public Task<EmergencyEscalation?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<EmergencyEscalation?>(null); public Task<(EmergencyEscalation Escalation, bool IsDuplicate)> AddOrGetDuplicateAsync(EmergencyEscalation e, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<EmergencyEscalation>> ListAsync(EmergencyEscalationQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<EmergencyEscalation>>([]); public Task<long> CountAsync(EmergencyEscalationQuery q, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(EmergencyEscalation e, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Telemetry : ITelemetrySummaryRepository { public Task<TripTelemetrySummary?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<TripTelemetrySummary?>(null); public Task<TripTelemetrySummary?> GetByTripIdAsync(string id, CancellationToken ct) => Task.FromResult<TripTelemetrySummary?>(null); public Task<TripTelemetrySummary?> GetByUserIdAndTripIdAsync(string u, string t, CancellationToken ct) => Task.FromResult<TripTelemetrySummary?>(null); public Task<TripTelemetrySummary> UpsertAsync(TripTelemetrySummary s, CancellationToken ct) => Task.FromResult(s); public Task<IReadOnlyList<TripTelemetrySummary>> ListByUserIdAsync(string u, TelemetrySummaryQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<TripTelemetrySummary>>([]); public Task<long> CountByUserIdAsync(string u, TelemetrySummaryQuery q, CancellationToken ct) => Task.FromResult(0L); public Task<IReadOnlyList<TripTelemetrySummary>> ListAsync(TelemetrySummaryQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<TripTelemetrySummary>>([]); public Task<long> CountAsync(TelemetrySummaryQuery q, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class Evidence : IEvidenceAttachmentRepository { public List<EvidenceAttachment> Items { get; } = []; public Task<EvidenceAttachment?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(e => e.Id == id)); public Task<EvidenceAttachment?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<EvidenceAttachment?>(null); public Task<EvidenceAttachment?> GetByClientEvidenceIdAsync(string u, string i, string c, CancellationToken ct) => Task.FromResult<EvidenceAttachment?>(null); public Task<(EvidenceAttachment EvidenceAttachment, bool IsDuplicate)> AddOrGetDuplicateAsync(EvidenceAttachment e, CancellationToken ct) => throw new NotImplementedException(); public Task UpdateAsync(EvidenceAttachment e, CancellationToken ct) => Task.CompletedTask; public Task<IReadOnlyList<EvidenceAttachment>> ListByUserIdAsync(string u, EvidenceAttachmentQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<EvidenceAttachment>>(Items.Where(e => e.UserId == u).ToArray()); public Task<long> CountByUserIdAsync(string u, EvidenceAttachmentQuery q, CancellationToken ct) => Task.FromResult(0L); public Task<IReadOnlyList<EvidenceAttachment>> ListAsync(EvidenceAttachmentQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<EvidenceAttachment>>([]); public Task<long> CountAsync(EvidenceAttachmentQuery q, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class Contacts : IMonitorLinkedContactRepository { public List<EmergencyContact> Items { get; } = []; public Task<IReadOnlyList<EmergencyContact>> GetActiveLinkedByLinkedUserIdAsync(string id, CancellationToken ct) => Task.FromResult<IReadOnlyList<EmergencyContact>>(Items.Where(c => c.LinkedUserId == id && c.IsActive && c.InvitationStatus == EmergencyContactInvitationStatus.Linked).ToArray()); }
    private sealed class AuditLogs : IAuditLogRepository { public Task AddAsync(AuditLogEntry e, CancellationToken ct) => Task.CompletedTask; public Task<AuditLogEntry?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<AuditLogEntry?>(null); public Task<IReadOnlyList<AuditLogEntry>> ListAsync(AuditLogQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<AuditLogEntry>>([]); public Task<long> CountAsync(AuditLogQuery q, CancellationToken ct) => Task.FromResult(0L); public Task<long> CountOlderThanAsync(DateTimeOffset cutoffUtc, CancellationToken ct) => Task.FromResult(0L); public Task<long> DeleteOlderThanAsync(DateTimeOffset cutoffUtc, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class Exports : IResolutionReportExportRepository { public List<ResolutionReportExport> Items { get; } = []; public Task<ResolutionReportExport?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(e => e.IdempotencyKey == k)); public Task<ResolutionReportExport> UpsertAsync(ResolutionReportExport e, CancellationToken ct) { Items.RemoveAll(x => x.IdempotencyKey == e.IdempotencyKey); Items.Add(e); return Task.FromResult(e); } public Task<IReadOnlyList<ResolutionReportExport>> ListAsync(ResolutionReportExportQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<ResolutionReportExport>>(Items); public Task<long> CountAsync(ResolutionReportExportQuery q, CancellationToken ct) => Task.FromResult((long)Items.Count); }
}
