using FluentAssertions;
using MotoSOS.API.Common.Abstractions;
using MotoSOS.API.Common.Exceptions;
using MotoSOS.API.Modules.AlertAcknowledgements.Application;
using MotoSOS.API.Modules.AlertAcknowledgements.Domain;
using MotoSOS.API.Modules.AlertDispatch.Application;
using MotoSOS.API.Modules.AlertDispatch.Domain;
using MotoSOS.API.Modules.AuditLogs.Application;
using MotoSOS.API.Modules.AuditLogs.Contracts;
using MotoSOS.API.Modules.AuditLogs.Domain;
using MotoSOS.API.Modules.EmergencyContacts.Domain;
using MotoSOS.API.Modules.EmergencyResolution.Application;
using MotoSOS.API.Modules.EmergencyResolution.Domain;
using MotoSOS.API.Modules.Escalations.Application;
using MotoSOS.API.Modules.Escalations.Domain;
using MotoSOS.API.Modules.EvidenceAttachments.Application;
using MotoSOS.API.Modules.EvidenceAttachments.Domain;
using MotoSOS.API.Modules.Incidents.Application;
using MotoSOS.API.Modules.Incidents.Domain;
using MotoSOS.API.Modules.LocationSharing.Application;
using MotoSOS.API.Modules.LocationSharing.Domain;
using MotoSOS.API.Modules.Notifications.Application;
using MotoSOS.API.Modules.Notifications.Domain;
using MotoSOS.API.Modules.ReportExports.Application;
using MotoSOS.API.Modules.ReportExports.Contracts;
using MotoSOS.API.Modules.ReportExports.Domain;
using MotoSOS.API.Modules.TelemetrySummary.Application;
using MotoSOS.API.Modules.TelemetrySummary.Domain;
using MotoSOS.API.Modules.Trips.Application;
using MotoSOS.API.Modules.Trips.Domain;
using MotoSOS.API.Modules.Users.Application;
using MotoSOS.API.Modules.Users.Domain;

namespace UnitTest.ReportExports;

public sealed class ResolutionReportExportServiceTests
{
    [Fact]
    public async Task RiderExportsOwnStructuredJsonWithSafeSummariesAndMetadataUpsert()
    {
        Ctx c = Ctx.Create();
        ResolutionReportExportResponse first = await c.Service.ExportForRiderAsync("rider", "incident", ResolutionReportExportType.Json, CancellationToken.None);
        ResolutionReportExportResponse second = await c.Service.ExportForRiderAsync("rider", "incident", ResolutionReportExportType.Json, CancellationToken.None);

        first.Header.ExportType.Should().Be("Json");
        first.IncidentSummary.IncidentId.Should().Be("incident");
        first.TripSummary.TripId.Should().Be("trip");
        first.AlertSummary.NotificationsTotal.Should().Be(2);
        first.AcknowledgementSummary.AcknowledgedCount.Should().Be(1);
        first.LocationSummary.LastKnownLatitude.Should().Be(19);
        first.ResolutionSummary.Outcome.Should().Be("RealEmergency");
        first.EscalationSummary.EscalationStatus.Should().Be("Requested");
        first.TelemetrySummary!.TotalMinorEvents.Should().Be(3);
        first.EvidenceSummary.Should().ContainSingle();
        first.EvidenceSummary.Single().EvidenceAttachmentId.Should().Be("evidence");
        first.AuditSummary.TotalAuditEvents.Should().Be(2);
        c.Exports.Items.Should().ContainSingle();
        second.Header.GeneratedAtUtc.Should().Be(first.Header.GeneratedAtUtc);
    }

    [Fact]
    public async Task RiderForeignAdminAnyAndMonitorAssignmentRulesAreEnforced()
    {
        Ctx c = Ctx.Create();
        await Assert.ThrowsAsync<NotFoundAppException>(() => c.Service.ExportForRiderAsync("other", "incident", ResolutionReportExportType.Json, CancellationToken.None));
        (await c.Service.ExportForAdminAsync("admin", "incident", ResolutionReportExportType.Json, CancellationToken.None)).Header.GeneratedByRole.Should().Be("Admin");
        (await c.Service.ExportForMonitorAsync("monitor", "attempt-1", ResolutionReportExportType.Json, CancellationToken.None)).Header.GeneratedByRole.Should().Be("Monitor");
        await Assert.ThrowsAsync<NotFoundAppException>(() => Ctx.Create(assigned: false).Service.ExportForMonitorAsync("monitor", "attempt-1", ResolutionReportExportType.Json, CancellationToken.None));
    }

    [Fact]
    public async Task MissingResolutionReportThrowsAndAuditFailureDoesNotBreak()
    {
        await Assert.ThrowsAsync<ReportExportNotAvailableAppException>(() => Ctx.Create(withReport: false).Service.ExportForRiderAsync("rider", "incident", ResolutionReportExportType.Json, CancellationToken.None));
        (await Ctx.Create(audit: new FailingAudit()).Service.ExportForRiderAsync("rider", "incident", ResolutionReportExportType.Json, CancellationToken.None)).Header.IncidentId.Should().Be("incident");
    }

    private static readonly DateTimeOffset Now = new(2026, 8, 9, 12, 0, 0, TimeSpan.Zero);
    private sealed class Ctx { public Exports Exports { get; private set; } = null!; public ResolutionReportExportService Service { get; private set; } = null!; public static Ctx Create(bool assigned = true, bool withReport = true, IAuditLogService? audit = null) { var c = new Ctx(); c.Exports = new Exports(); var incident = new Incident { Id = "incident", UserId = "rider", TripId = "trip", Cause = IncidentCause.CountdownTimeout, RiskLevel = IncidentRiskLevel.High, Status = IncidentStatus.Closed, OccurredAtUtc = Now.AddMinutes(-30), CreatedAtUtc = Now.AddMinutes(-30), ClosedAtUtc = Now.AddMinutes(-5) }; var report = new EmergencyResolutionReport { Id = "report", UserId = "rider", IncidentId = "incident", TripId = "trip", AlertDispatchId = "alert", Outcome = EmergencyResolutionOutcome.RealEmergency, ClosedByRole = EmergencyClosedByRole.Rider, CreatedAtUtc = Now.AddMinutes(-4), Summary = "safe", Notes = "safe notes", ResponseTimeSeconds = 120, LastKnownLocationWasStale = false }; c.Service = new ResolutionReportExportService(new Users(), new Incidents(incident), new Trips(new Trip { Id = "trip", UserId = "rider", VehicleId = "vehicle", Status = TripStatus.Finished, StartedAtUtc = Now.AddHours(-1), FinishedAtUtc = Now, CreatedAtUtc = Now.AddHours(-1) }), new Alerts(new AlertDispatchRequest { Id = "alert", UserId = "rider", IncidentId = "incident", TripId = "trip", Status = AlertDispatchStatus.Completed, ContactsSnapshot = [new AlertContactSnapshot { EmergencyContactId = "contact", FullName = "Name", Priority = 1, InvitationStatus = EmergencyContactInvitationStatus.Linked }], CreatedAtUtc = Now.AddMinutes(-20) }), new Notifications(), new Acks(), new Locations(), new Reports(withReport ? [report] : []), new Escalations(), new Telemetry(), new Evidence(), new Contacts(assigned), new Attempts(), new AuditRepo(), c.Exports, new ResolutionReportExportIdempotencyKeyFactory(), new Staleness(), new Clock(), audit ?? new Audit()); return c; } }
    private sealed class Clock : IClock { public DateTimeOffset UtcNow => Now; }
    private sealed class Users : IUserRepository { public Task<User?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<User?>(id switch { "rider" => new User { Id = id, Role = UserRole.Rider, IsActive = true }, "other" => new User { Id = id, Role = UserRole.Rider, IsActive = true }, "monitor" => new User { Id = id, Role = UserRole.Monitor, IsActive = true }, "admin" => new User { Id = id, Role = UserRole.Admin, IsActive = true }, _ => null }); public Task<User?> GetByEmailAsync(string email, CancellationToken ct) => Task.FromResult<User?>(null); public Task AddAsync(User user, CancellationToken ct) => Task.CompletedTask; public Task UpdateAsync(User user, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Incidents(params Incident[] items) : IIncidentRepository { public Task<Incident?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(items.FirstOrDefault(i => i.Id == id)); public Task<Incident?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<Incident?>(null); public Task<(Incident Incident, bool IsDuplicate)> AddOrGetDuplicateAsync(Incident i, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<Incident>> ListByUserIdAsync(string u, IncidentStatus? s, string? t, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<Incident>>([]); public Task<long> CountByUserIdAsync(string u, IncidentStatus? s, string? t, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(Incident i, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Trips(params Trip[] items) : ITripRepository { public Task<Trip?> GetActiveByUserIdAsync(string u, CancellationToken ct) => Task.FromResult<Trip?>(null); public Task<Trip?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(items.FirstOrDefault(t => t.Id == id)); public Task<IReadOnlyList<Trip>> ListByUserIdAsync(string u, TripStatus? s, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<Trip>>([]); public Task<long> CountByUserIdAsync(string u, TripStatus? s, CancellationToken ct) => Task.FromResult(0L); public Task AddAsync(Trip t, CancellationToken ct) => Task.CompletedTask; public Task UpdateAsync(Trip t, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Alerts(params AlertDispatchRequest[] items) : IAlertDispatchRepository { public Task<AlertDispatchRequest?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(items.FirstOrDefault(a => a.Id == id)); public Task<AlertDispatchRequest?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<AlertDispatchRequest?>(null); public Task<(AlertDispatchRequest AlertDispatch, bool IsDuplicate)> AddOrGetDuplicateAsync(AlertDispatchRequest a, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<AlertDispatchRequest>> ListByUserIdAsync(string u, AlertDispatchStatus? s, string? i, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<AlertDispatchRequest>>(items.Where(a => a.UserId == u && (i is null || a.IncidentId == i)).ToArray()); public Task<long> CountByUserIdAsync(string u, AlertDispatchStatus? s, string? i, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(AlertDispatchRequest a, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Notifications : INotificationDeliveryAttemptRepository { private readonly NotificationDeliveryAttempt[] _items = [new() { Id = "attempt-1", UserId = "rider", AlertDispatchId = "alert", IncidentId = "incident", EmergencyContactId = "contact", Status = NotificationDeliveryStatus.Prepared, CreatedAtUtc = Now }, new() { Id = "attempt-2", UserId = "rider", AlertDispatchId = "alert", IncidentId = "incident", EmergencyContactId = "contact", Status = NotificationDeliveryStatus.SimulatedSent, CreatedAtUtc = Now }]; public Task<NotificationDeliveryAttempt?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(_items.FirstOrDefault(a => a.Id == id)); public Task<NotificationDeliveryAttempt?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<NotificationDeliveryAttempt?>(null); public Task<(NotificationDeliveryAttempt Attempt, bool IsDuplicate)> AddOrGetDuplicateAsync(NotificationDeliveryAttempt a, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<NotificationDeliveryAttempt>> ListByUserIdAsync(string u, string? a, string? i, NotificationDeliveryStatus? s, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<NotificationDeliveryAttempt>>(_items.Where(n => n.UserId == u && (a is null || n.AlertDispatchId == a) && (i is null || n.IncidentId == i)).ToArray()); public Task<long> CountByUserIdAsync(string u, string? a, string? i, NotificationDeliveryStatus? s, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(NotificationDeliveryAttempt a, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Acks : IAlertAcknowledgementRepository { private readonly AlertAcknowledgement[] _items = [new() { UserId = "rider", AlertDispatchId = "alert", IncidentId = "incident", Status = AlertAcknowledgementStatus.Acknowledged, AcknowledgedAtUtc = Now }]; public Task<AlertAcknowledgement?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<AlertAcknowledgement?>(null); public Task<AlertAcknowledgement?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<AlertAcknowledgement?>(null); public Task<(AlertAcknowledgement Acknowledgement, bool IsDuplicate)> AddOrGetDuplicateAsync(AlertAcknowledgement a, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<AlertAcknowledgement>> ListByMonitorUserIdAsync(string m, AlertAcknowledgementStatus? s, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<AlertAcknowledgement>>([]); public Task<long> CountByMonitorUserIdAsync(string m, AlertAcknowledgementStatus? s, CancellationToken ct) => Task.FromResult(0L); public Task<IReadOnlyList<AlertAcknowledgement>> ListByUserIdAsync(string u, string? a, string? i, AlertAcknowledgementStatus? s, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<AlertAcknowledgement>>(_items.Where(x => x.UserId == u && (a is null || x.AlertDispatchId == a) && (i is null || x.IncidentId == i)).ToArray()); public Task<long> CountByUserIdAsync(string u, string? a, string? i, AlertAcknowledgementStatus? s, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(AlertAcknowledgement a, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Locations : ILocationSharingRepository { public Task<EmergencyLocationSnapshot?> GetByUserIdAndIncidentIdAsync(string u, string i, CancellationToken ct) => Task.FromResult<EmergencyLocationSnapshot?>(null); public Task<EmergencyLocationSnapshot?> GetActiveByIncidentIdAsync(string i, CancellationToken ct) => GetLatestByIncidentIdAsync(i, ct); public Task<EmergencyLocationSnapshot?> GetLatestByIncidentIdAsync(string i, CancellationToken ct) => Task.FromResult<EmergencyLocationSnapshot?>(new EmergencyLocationSnapshot { IncidentId = i, Latitude = 19, Longitude = -99, RecordedAtUtc = Now }); public Task<EmergencyLocationSnapshot> UpsertLatestAsync(EmergencyLocationSnapshot s, CancellationToken ct) => Task.FromResult(s); }
    private sealed class Reports(EmergencyResolutionReport[] items) : IEmergencyResolutionRepository { public Task<EmergencyResolutionReport?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult(items.FirstOrDefault(r => r.Id == id)); public Task<EmergencyResolutionReport?> GetByIncidentIdAsync(string i, CancellationToken ct) => Task.FromResult(items.FirstOrDefault(r => r.IncidentId == i)); public Task<EmergencyResolutionReport?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<EmergencyResolutionReport?>(null); public Task<(EmergencyResolutionReport Report, bool IsDuplicate)> AddOrGetDuplicateAsync(EmergencyResolutionReport r, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<EmergencyResolutionReport>> ListByUserIdAsync(string u, EmergencyResolutionOutcome? o, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<EmergencyResolutionReport>>([]); public Task<long> CountByUserIdAsync(string u, EmergencyResolutionOutcome? o, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class Escalations : IEmergencyEscalationRepository { public Task<EmergencyEscalation?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<EmergencyEscalation?>(null); public Task<EmergencyEscalation?> GetByAlertDispatchIdAsync(string id, CancellationToken ct) => Task.FromResult<EmergencyEscalation?>(new EmergencyEscalation { AlertDispatchId = id, Status = EmergencyEscalationStatus.Requested, Reason = EmergencyEscalationReason.NoAcknowledgement, Level = EmergencyEscalationLevel.Level1, CreatedAtUtc = Now }); public Task<EmergencyEscalation?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<EmergencyEscalation?>(null); public Task<(EmergencyEscalation Escalation, bool IsDuplicate)> AddOrGetDuplicateAsync(EmergencyEscalation e, CancellationToken ct) => throw new NotImplementedException(); public Task<IReadOnlyList<EmergencyEscalation>> ListAsync(EmergencyEscalationQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<EmergencyEscalation>>([]); public Task<long> CountAsync(EmergencyEscalationQuery q, CancellationToken ct) => Task.FromResult(0L); public Task UpdateAsync(EmergencyEscalation e, CancellationToken ct) => Task.CompletedTask; }
    private sealed class Telemetry : ITelemetrySummaryRepository { public Task<TripTelemetrySummary?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<TripTelemetrySummary?>(null); public Task<TripTelemetrySummary?> GetByTripIdAsync(string id, CancellationToken ct) => Task.FromResult<TripTelemetrySummary?>(new TripTelemetrySummary { TripId = id, TotalMinorEvents = 3, EventsByType = new Dictionary<string, int> { ["HardBrake"] = 1 }, EventsBySeverity = new Dictionary<string, int>(), EventsBySource = new Dictionary<string, int>(), HardBrakeCount = 1 }); public Task<TripTelemetrySummary?> GetByUserIdAndTripIdAsync(string u, string t, CancellationToken ct) => GetByTripIdAsync(t, ct); public Task<TripTelemetrySummary> UpsertAsync(TripTelemetrySummary s, CancellationToken ct) => Task.FromResult(s); public Task<IReadOnlyList<TripTelemetrySummary>> ListByUserIdAsync(string u, TelemetrySummaryQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<TripTelemetrySummary>>([]); public Task<long> CountByUserIdAsync(string u, TelemetrySummaryQuery q, CancellationToken ct) => Task.FromResult(0L); public Task<IReadOnlyList<TripTelemetrySummary>> ListAsync(TelemetrySummaryQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<TripTelemetrySummary>>([]); public Task<long> CountAsync(TelemetrySummaryQuery q, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class Evidence : IEvidenceAttachmentRepository { public Task<EvidenceAttachment?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<EvidenceAttachment?>(null); public Task<EvidenceAttachment?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult<EvidenceAttachment?>(null); public Task<(EvidenceAttachment EvidenceAttachment, bool IsDuplicate)> AddOrGetDuplicateAsync(EvidenceAttachment e, CancellationToken ct) => throw new NotImplementedException(); public Task UpdateAsync(EvidenceAttachment e, CancellationToken ct) => Task.CompletedTask; public Task<IReadOnlyList<EvidenceAttachment>> ListByUserIdAsync(string u, EvidenceAttachmentQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<EvidenceAttachment>>([new EvidenceAttachment { Id = "evidence", UserId = u, IncidentId = "incident", TargetType = EvidenceTargetType.Incident, EvidenceType = EvidenceType.Photo, Source = EvidenceSource.RiderMobileApp, Status = EvidenceAttachmentStatus.Registered, FileName = "photo.jpg", ContentType = "image/jpeg", SizeBytes = 10, RegisteredByRole = UserRole.Rider, CapturedAtUtc = Now, CreatedAtUtc = Now, ClientStorageReference = "local://hidden", StorageObjectKey = "hidden", Metadata = new Dictionary<string, string> { ["hidden"] = "hidden" } }]); public Task<long> CountByUserIdAsync(string u, EvidenceAttachmentQuery q, CancellationToken ct) => Task.FromResult(1L); public Task<IReadOnlyList<EvidenceAttachment>> ListAsync(EvidenceAttachmentQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<EvidenceAttachment>>([]); public Task<long> CountAsync(EvidenceAttachmentQuery q, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class Contacts(bool assigned) : IMonitorLinkedContactRepository { public Task<IReadOnlyList<EmergencyContact>> GetActiveLinkedByLinkedUserIdAsync(string id, CancellationToken ct) => Task.FromResult<IReadOnlyList<EmergencyContact>>(assigned ? [new EmergencyContact { Id = "contact", LinkedUserId = id, IsActive = true, InvitationStatus = EmergencyContactInvitationStatus.Linked }] : []); }
    private sealed class Attempts : INotificationAttemptMonitorRepository { public Task<NotificationDeliveryAttempt?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<NotificationDeliveryAttempt?>(new NotificationDeliveryAttempt { Id = id, UserId = "rider", AlertDispatchId = "alert", IncidentId = "incident", EmergencyContactId = "contact" }); public Task<IReadOnlyList<NotificationDeliveryAttempt>> ListByEmergencyContactIdsAsync(IReadOnlyCollection<string> ids, int p, int z, CancellationToken ct) => Task.FromResult<IReadOnlyList<NotificationDeliveryAttempt>>([]); public Task<long> CountByEmergencyContactIdsAsync(IReadOnlyCollection<string> ids, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class AuditRepo : IAuditLogRepository { public Task AddAsync(AuditLogEntry e, CancellationToken ct) => Task.CompletedTask; public Task<AuditLogEntry?> GetByIdAsync(string id, CancellationToken ct) => Task.FromResult<AuditLogEntry?>(null); public Task<IReadOnlyList<AuditLogEntry>> ListAsync(AuditLogQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<AuditLogEntry>>([new AuditLogEntry { Action = AuditAction.IncidentClosed, CreatedAtUtc = Now }]); public Task<long> CountAsync(AuditLogQuery q, CancellationToken ct) => Task.FromResult(1L); public Task<long> CountOlderThanAsync(DateTimeOffset cutoffUtc, CancellationToken ct) => Task.FromResult(0L); public Task<long> DeleteOlderThanAsync(DateTimeOffset cutoffUtc, CancellationToken ct) => Task.FromResult(0L); }
    private sealed class Exports : IResolutionReportExportRepository { public List<ResolutionReportExport> Items { get; } = []; public Task<ResolutionReportExport?> GetByIdempotencyKeyAsync(string k, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(e => e.IdempotencyKey == k)); public Task<ResolutionReportExport> UpsertAsync(ResolutionReportExport e, CancellationToken ct) { Items.RemoveAll(x => x.IdempotencyKey == e.IdempotencyKey); Items.Add(e); return Task.FromResult(e); } public Task<IReadOnlyList<ResolutionReportExport>> ListAsync(ResolutionReportExportQuery q, CancellationToken ct) => Task.FromResult<IReadOnlyList<ResolutionReportExport>>(Items); public Task<long> CountAsync(ResolutionReportExportQuery q, CancellationToken ct) => Task.FromResult((long)Items.Count); }
    private sealed class Staleness : ILocationSharingStalenessService { public bool IsStale(DateTimeOffset recordedAtUtc, DateTimeOffset now) => false; }
    private class Audit : IAuditLogService { public Task RecordAsync(string actorUserId, string actorRole, AuditAction action, AuditModule module, string entityType, string? entityId, AuditOutcome outcome, string? reason, string? requestPath, string? httpMethod, IReadOnlyDictionary<string, string>? metadata, CancellationToken cancellationToken) => Task.CompletedTask; public Task<GetAuditLogsResponse> ListAsync(string adminUserId, AuditLogQuery query, CancellationToken cancellationToken) => throw new NotImplementedException(); public Task<AuditLogResponse> GetAsync(string adminUserId, string id, CancellationToken cancellationToken) => throw new NotImplementedException(); }
    private sealed class FailingAudit : Audit { public new Task RecordAsync(string actorUserId, string actorRole, AuditAction action, AuditModule module, string entityType, string? entityId, AuditOutcome outcome, string? reason, string? requestPath, string? httpMethod, IReadOnlyDictionary<string, string>? metadata, CancellationToken cancellationToken) => throw new InvalidOperationException("audit failed"); }
}
