namespace MotoSOS.API.Modules.EvidenceAttachments.Contracts;

public sealed record EvidenceAttachmentResponse(
    string Id,
    string UserId,
    string RegisteredByUserId,
    string RegisteredByRole,
    string TargetType,
    string? IncidentId,
    string? AlertDispatchId,
    string? EmergencyResolutionReportId,
    string? TripId,
    string EvidenceType,
    string Source,
    string Status,
    string FileName,
    string ContentType,
    long SizeBytes,
    string? Sha256Hash,
    string ClientEvidenceId,
    string? ClientStorageReference,
    string StorageProvider,
    string? Description,
    DateTimeOffset CapturedAtUtc,
    DateTimeOffset RegisteredAtUtc,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    DateTimeOffset? DeletedAtUtc,
    IReadOnlyDictionary<string, string> Metadata);
