namespace MotoSOS.API.Modules.OperationalDashboard.Contracts;

public sealed record OperationalDashboardResolutionOutcomesResponse(IReadOnlyList<OperationalDashboardResolutionOutcomeItemResponse> Items);
